### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [ghostrepo0/cdn_movies#10]
Кода не очень много, поэтому я придирался ко всему подряд :)
1. nit: Жаль что вы не переехали на python 3.10 он уже давно стабилен и готов к использованию. Новые возможности, в том числе новый синтаксис позволяет отказаться от модуля Typing https://docs.python.org/3/whatsnew/3.10.html#pep-604-new-type-union-operator
2. [Вот тут](https://github.com/ghostrepo0/cdn_movies/blob/9f03da61db53662b78c81a244855eabb14516bd0/etl/common/etl_config.py#L7) можно было и не указывать имена переменных окружения, по умолчанию у pydantic-сеттингов маппинг регистронезависимый, т.е. в поле `batch_size` присвоится значение переменной окружения `BATCH_SIZE`
3. Обратите внимание на https://okomestudio.net/biboroku/2020/04/on-lazy-logging-evaluation/. Можно применить к вашему логированию
4. Начиная с версии python 3.9 для стандартных [коллекций](https://github.com/ghostrepo0/cdn_movies/blob/9f03da61db53662b78c81a244855eabb14516bd0/etl/models/models.py#L32) больше не нужен модуль typing: https://docs.python.org/3.9/whatsnew/3.9.html#type-hinting-generics-in-standard-collections. А в python 3.10 это выглядело бы `role: list[PersonRole] | None = None`
5. А [вот тут](https://github.com/ghostrepo0/cdn_movies/blob/9f03da61db53662b78c81a244855eabb14516bd0/moives_api/api/v1/films.py#L41) специально не используете https://pydantic-docs.helpmanual.io/usage/models/#helper-functions или просто забыли?

**Comment by ghostrepo0** [comment]
1. 😐;
2. Нам удобнее явно прописывать как называется переменная в окружении, легче ревью проводить));
3. Добавил;
4. Исправил;
5. Да, для того чтобы явно показать какие поля используются, хотя обе модели и одинаковые. Чтобы в будущем лишний раз по проекту не прыгать.

[Исправления](https://github.com/ghostrepo0/cdn_movies/commit/93bbb909667cf129e4e1bfa20e796fe18ca0b7ae)

**Comment by BigDeepBlue** [comment]
LGTM
